# This is a basic workflow to help you get started with Actions

name: 编译EXE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - name: 编译
        run: |
           zig build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
      # Artifact name
         name: github-actions-build
      # A file, directory or wildcard pattern that describes what to upload
         path: |
            zig-out/bin/*.exe
         if-no-files-found: error
